# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        your_mapping_name:
            uri_prefix: '/uploads'  # Remplacez par le préfixe que vous souhaitez utiliser
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
