vich_uploader:
    db_driver: orm

    mappings:
       vehicle_image:
            uri_prefix: '/uploads/vehicles/images'
            upload_destination: '%kernel.project_dir%/public/uploads/vehicles/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
